In [1]:
import numpy as np
import torch

In [5]:
t = np.array([[[0,1,2],
            [3,4,5]],
            [[6,7,8],
            [9,10,11]]])

ft = torch.FloatTensor([[[0,1,2],
            [3,4,5]],
            [[6,7,8],
            [9,10,11]]])

In [6]:
print(t.shape)
print(ft.shape)

(2, 2, 3)
torch.Size([2, 2, 3])


In [10]:
print(ft)
print(ft.view([-1, 3]))

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])


In [13]:
print(ft.view([-1,1,3]))

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
