In [1]:
import numpy as np 

In [10]:
# t = np.array([[0. ,1. ,2., 3.,4],[0. ,1. ,2., 3.,4]])
t = np.array([0. ,1. ,2., 3.,4])

In [11]:
t

array([0., 1., 2., 3., 4.])

In [13]:
print("Rank of t: ",t.ndim)
print("Shape of t: ",t.shape)

Rank of t:  1
Shape of t:  (5,)


In [15]:
t[1]

1.0

In [22]:
t[1:]

array([1., 2., 3., 4.])

In [2]:
import torch

In [19]:
tt = torch.FloatTensor([[0.,1.,2.,3.,4.],
                        [5.,6.,7.,8.,9.],
                        [10.,11.,12.,13.,14.]
                        ])
print(tt)

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.]])


In [20]:
print(tt.dim())
print(tt.shape)
print(tt.size())

2
torch.Size([3, 5])
torch.Size([3, 5])


In [22]:
tt[1:,1:3].size()

torch.Size([2, 2])

In [26]:
m1 = torch.FloatTensor([[1, 2],[3,4]])
m2 = torch.FloatTensor([[1], [2]])

In [27]:
m2.size()

torch.Size([2, 1])

In [29]:
print(m1.matmul(m2))
print(m1*m2)

tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])


In [30]:
print(m1)

tensor([[1., 2.],
        [3., 4.]])


In [32]:
m1.mean()

tensor(2.5000)

In [34]:
print(m1.mean(dim=0))
print(m1.mean(dim=1))

tensor([2., 3.])
tensor([1.5000, 3.5000])


In [36]:
m1.max()

tensor(4.)

In [42]:
m1.max(dim=0)

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

In [46]:
m1.argmax()

tensor(3)